---
title: "Check stats datasets"
author: "Eve Zeyl Fiskebeck"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  prepdata_dir: "data/prepared_data" 
  results_dir: "results"
execute: 
  echo: false
  cache: false
format: html
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
---

```{r setup }
library(here)
library(tidyverse)
library(readxl)
library(xlsx)
library(plyr)
library(seqinr)
```


```{r}
HA_init_file <- here::here("results", "H5N1_HA_all", "msa", "H5N1_initial_ref_MSA_jalview.fasta")
HA_init <- read.fasta(HA_init_file)

names_HA_init <- unlist(getAnnot(HA_init)) 
length(names_HA_init)

seq_HA_init <- unlist(getSequence(HA_init, as.string = T)) %>%
  str_remove_all(., "-")

HA_init_df <- tibble("header" = names_HA_init, 
                     "sequence" = seq_HA_init) %>%
  mutate(length = str_length(sequence))

max(HA_init_df$length)
```


```{r}
NA_init_file <- here::here("results", "H5N1_NA", "MSA", "NA_N1_initial_alignment.fasta")
NA_init <- read.fasta(NA_init_file)

names_NA_init <- unlist(getAnnot(NA_init)) 
length(names_NA_init)

seq_NA_init <- unlist(getSequence(NA_init, as.string = T)) %>%
  str_remove_all(., "-")

NA_init_df <- tibble("header" = names_NA_init, 
                     "sequence" = seq_NA_init) %>%
  mutate(length = str_length(sequence))

max(NA_init_df$length)
```

# checking length for NVI sequences

```{r}
all_tree_metadata <- readRDS(here::here("data", "prepared_data", "all_tree_metadata_CAB.RDS"))
```

H5N5 HA 
```{r}
H5N5_HA_file <- here::here("results", "H5N5_HA", "iqtree", "H5N5_all_SEP_MSA_jalview.fasta")
H5N5_HA_data <- read.fasta(H5N5_HA_file) 
H5N5_HA_names <- unlist(getAnnot(H5N5_HA_data)) %>%
  str_remove_all(">.*\\|") %>%
  str_remove_all("\\/.*$") %>%
  str_remove_all("(c$)|(_tr$)")

H5N5_HA_seq <- unlist(getSequence(H5N5_HA_data, as.string = T)) %>%
  str_remove_all(., "-")
  
H5N5_HA_df <- tibble("names" = H5N5_HA_names, 
                     "seq" = H5N5_HA_seq) 

H5N5_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country == "Norway") %>%
  pull(seq) %>%
  str_length() %>%
  range()

H5N5_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country != "Norway") %>%
  #filter(Isolate_Id != "EPI_ISL_177506", Isolate_Id != "EPI_ISL_1254") %>%
  pull(seq) %>%
  str_length() %>%
  range()
```

The H5N5 sample that was removed (dup)
```{r}
H5N5_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(Isolate_ID == "Norway") %>%
  #filter(Isolate_Id != "EPI_ISL_177506", Isolate_Id != "EPI_ISL_1254") %>%
  pull(seq) %>%
  str_length() %>%
  range()

# the lengt of removed isolate
H5N5_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(Isolate_Id == "EPI_ISL_12028892") %>%
  pull(seq) %>%
  str_length() 
  
H5N5_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(Isolate_Id != "EPI_ISL_12028892") %>%
  pull(seq) %>%
  str_length() %>%
  range()
```


H5N5 NA 
```{r}
H5N5_NA_file <- here::here("results", "H5N5_NA", "iqtree", "SEP_NA_H5N5_clean_total_jalview_alignment.fasta")
H5N5_NA_data <- read.fasta(H5N5_NA_file) 
H5N5_NA_names <- unlist(getAnnot(H5N5_NA_data)) %>%
  str_remove_all(">.*\\|") %>%
  str_remove_all("\\/.*$") %>%
  str_remove_all("(c$)|(_tr$)")

H5N5_NA_seq <- unlist(getSequence(H5N5_NA_data, as.string = T)) %>%
  str_remove_all(., "-")
  
H5N5_NA_df <- tibble("names" = H5N5_NA_names, 
                     "seq" = H5N5_NA_seq) 

H5N5_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country == "Norway") %>%
  #filter(is.na(Isolate_Id))
  pull(seq) %>%
  str_length() %>%
  range()

H5N5_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country != "Norway") %>%
  pull(seq) %>%
  str_length() %>%
  range()

# the lengt of removed isolate
H5N5_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(Isolate_Id == "EPI_ISL_12028892") %>%
  pull(seq) %>%
  str_length() 
  
H5N5_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(Isolate_Id != "EPI_ISL_12028892") %>%
  pull(seq) %>%
  str_length() %>%
  range()
```

H5N1  HA

```{r}
H5N1_HA_file <- here::here("results", "H5N1_HA_all", "iqtree", "SEP_HA_H5N1_MSA_nomammals.fasta")
H5N1_HA_data <- read.fasta(H5N1_HA_file) 
H5N1_HA_names <- unlist(getAnnot(H5N1_HA_data)) %>%
  str_remove_all(">.*\\|") %>%
  str_remove_all("\\/.*$") %>%
  str_remove_all("(c$)|(_tr$)")

H5N1_HA_seq <- unlist(getSequence(H5N1_HA_data, as.string = T)) %>%
  str_remove_all(., "-")
  
H5N1_HA_df <- tibble("names" = H5N1_HA_names, 
                     "seq" = H5N1_HA_seq) 

H5N1_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country == "Norway") %>%
  #filter(is.na(Isolate_Id))
  pull(seq) %>%
  str_length() %>%
  range()

H5N1_HA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country != "Norway") %>%
  #filter(Isolate_Id != "EPI_ISL_177506", Isolate_Id != "EPI_ISL_1254") %>%
  pull(seq) %>%
  str_length() %>%
  range()
```


H5N1  NA

```{r}
H5N1_NA_file <- here::here("results", "H5N1_NA", "iqtree", "SEP_NA_H5N1_MSA_nommals.fasta")
H5N1_NA_data <- read.fasta(H5N1_NA_file) 
H5N1_NA_names <- unlist(getAnnot(H5N1_NA_data)) %>%
  str_remove_all(">.*\\|") %>%
  str_remove_all("\\/.*$") %>%
  str_remove_all("(c$)|(_tr$)")

H5N1_NA_seq <- unlist(getSequence(H5N1_NA_data, as.string = T)) %>%
  str_remove_all(., "-")
  
H5N1_NA_df <- tibble("names" = H5N1_NA_names, 
                     "seq" = H5N1_NA_seq) 

H5N1_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country == "Norway") %>%
  #filter(is.na(Isolate_Id))
  pull(seq) %>%
  str_length() %>%
  range()

H5N1_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country != "Norway") %>%
  #filter(Isolate_Id != "EPI_ISL_177506", Isolate_Id != "EPI_ISL_1254") %>%
  pull(seq) %>%
  str_length() %>%
  range()

H5N1_NA_df %>% 
  left_join(all_tree_metadata, by = c("names" = "label")) %>%
  filter(country != "Norway") %>%
  filter(Isolate_Id != "EPI_ISL_177506", Isolate_Id != "EPI_ISL_1254") %>%
  pull(seq) %>%
  str_length() %>%
  range()
```

